dist: trusty
sudo: required
addons:
  apt:
    packages:
      - cmake
      - iverilog
      - avr-libc
language: c
install:
  - mkdir build
  - (cd build && cmake ..)
  - make -C build -j2 VERBOSE=1
script: (cd build && ctest --output-on-failure)
